/**
 * Emits src/glasses/metrics.ts from the pretext font tables.
 *
 * pretext ships metrics for every firmware font, CJK and emoji included:
 * 118 KB, over half the bundle. This app draws 57 characters, so the generated
 * table holds the widths and kerning pairs for exactly those.
 *
 * Run after changing any string the glasses render: npm run gen:metrics
 */
import { getTextWidth } from '@evenrealities/pretext'
import { writeFileSync } from 'node:fs'

/** Every character the glasses layout can produce. */
const CHARSET = ' ABCDEFGHIJKLMNOPQRSTUVWXYZbz0123456789.+-/#[]·═─╪┼♭♯┬█◆▲●○'

const chars = [...CHARSET]
const widths = chars.map((c) => [c, getTextWidth(c)])

// Kerning as the pixel difference between a pair and its glyphs alone.
// Verified exact against pretext over 20k random strings in this charset.
const byDelta = new Map()
for (const a of chars) {
  for (const b of chars) {
    const d = getTextWidth(a + b) - getTextWidth(a) - getTextWidth(b)
    if (d === 0) continue
    if (!byDelta.has(d)) byDelta.set(d, [])
    byDelta.get(d).push(a + b)
  }
}

const deltaEntries = [...byDelta.entries()].sort((x, y) => x[0] - y[0])

const src = `// Generated by scripts/gen-metrics.mjs. Do not edit.
// Firmware font metrics for the characters this app draws.
//
// Derived from @evenrealities/pretext (MIT), which is a build-time dependency
// and is not itself bundled.

const WIDTHS: Record<string, number> = {
${widths.map(([c, w]) => `  ${JSON.stringify(c)}: ${w},`).join('\n')}
}

// Kerning pairs, grouped by their pixel adjustment.
const KERNS: ReadonlyArray<readonly [number, string]> = [
${deltaEntries.map(([d, pairs]) => `  [${d}, ${JSON.stringify(pairs.join(''))}],`).join('\n')}
]

const KERN = new Map<string, number>()
for (const [delta, pairs] of KERNS) {
  for (let i = 0; i < pairs.length; i += 2) KERN.set(pairs.slice(i, i + 2), delta)
}

/** Fallback for a character outside the generated set. */
const DEFAULT_WIDTH = ${Math.round(widths.reduce((t, [, w]) => t + w, 0) / widths.length)}

/**
 * Width in pixels of a string in the firmware font.
 *
 * Matches @evenrealities/pretext exactly for this charset. Kerning is real
 * here: ignoring it puts common rows up to 13px out, which is enough to push
 * text past a container edge, where it wraps to an invisible second line.
 */
export function textWidth(s: string): number {
  let total = 0
  for (let i = 0; i < s.length; i++) {
    total += WIDTHS[s[i]] ?? DEFAULT_WIDTH
    if (i + 1 < s.length) total += KERN.get(s[i] + s[i + 1]) ?? 0
  }
  return total
}
`

writeFileSync('src/glasses/metrics.ts', src)
console.log(
  `metrics.ts: ${chars.length} chars, ${deltaEntries.reduce((t, [, p]) => t + p.length, 0)} kern pairs, ${(src.length / 1024).toFixed(1)} KB source`,
)
